/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppWeighingsRouteImport } from './routes/_authenticated.app.weighings'
import { Route as AuthenticatedAppTasksRouteImport } from './routes/_authenticated.app.tasks'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated.app.settings'
import { Route as AuthenticatedAppSeasonsRouteImport } from './routes/_authenticated.app.seasons'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated.app.reports'
import { Route as AuthenticatedAppPlotsRouteImport } from './routes/_authenticated.app.plots'
import { Route as AuthenticatedAppHealthRouteImport } from './routes/_authenticated.app.health'
import { Route as AuthenticatedAppHarvestsRouteImport } from './routes/_authenticated.app.harvests'
import { Route as AuthenticatedAppFinanceRouteImport } from './routes/_authenticated.app.finance'
import { Route as AuthenticatedAppApplicationsRouteImport } from './routes/_authenticated.app.applications'
import { Route as AuthenticatedAppAnimalsRouteImport } from './routes/_authenticated.app.animals'
import { Route as AuthenticatedAppAlertsRouteImport } from './routes/_authenticated.app.alerts'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated.app.admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWeighingsRoute =
  AuthenticatedAppWeighingsRouteImport.update({
    id: '/weighings',
    path: '/weighings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTasksRoute = AuthenticatedAppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeasonsRoute = AuthenticatedAppSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPlotsRoute = AuthenticatedAppPlotsRouteImport.update({
  id: '/plots',
  path: '/plots',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHealthRoute = AuthenticatedAppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHarvestsRoute =
  AuthenticatedAppHarvestsRouteImport.update({
    id: '/harvests',
    path: '/harvests',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinanceRoute = AuthenticatedAppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppApplicationsRoute =
  AuthenticatedAppApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAnimalsRoute = AuthenticatedAppAnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAlertsRoute = AuthenticatedAppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/animals': typeof AuthenticatedAppAnimalsRoute
  '/app/applications': typeof AuthenticatedAppApplicationsRoute
  '/app/finance': typeof AuthenticatedAppFinanceRoute
  '/app/harvests': typeof AuthenticatedAppHarvestsRoute
  '/app/health': typeof AuthenticatedAppHealthRoute
  '/app/plots': typeof AuthenticatedAppPlotsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/seasons': typeof AuthenticatedAppSeasonsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/weighings': typeof AuthenticatedAppWeighingsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/animals': typeof AuthenticatedAppAnimalsRoute
  '/app/applications': typeof AuthenticatedAppApplicationsRoute
  '/app/finance': typeof AuthenticatedAppFinanceRoute
  '/app/harvests': typeof AuthenticatedAppHarvestsRoute
  '/app/health': typeof AuthenticatedAppHealthRoute
  '/app/plots': typeof AuthenticatedAppPlotsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/seasons': typeof AuthenticatedAppSeasonsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/weighings': typeof AuthenticatedAppWeighingsRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/_authenticated/app/animals': typeof AuthenticatedAppAnimalsRoute
  '/_authenticated/app/applications': typeof AuthenticatedAppApplicationsRoute
  '/_authenticated/app/finance': typeof AuthenticatedAppFinanceRoute
  '/_authenticated/app/harvests': typeof AuthenticatedAppHarvestsRoute
  '/_authenticated/app/health': typeof AuthenticatedAppHealthRoute
  '/_authenticated/app/plots': typeof AuthenticatedAppPlotsRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/seasons': typeof AuthenticatedAppSeasonsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/tasks': typeof AuthenticatedAppTasksRoute
  '/_authenticated/app/weighings': typeof AuthenticatedAppWeighingsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app'
    | '/app/admin'
    | '/app/alerts'
    | '/app/animals'
    | '/app/applications'
    | '/app/finance'
    | '/app/harvests'
    | '/app/health'
    | '/app/plots'
    | '/app/reports'
    | '/app/seasons'
    | '/app/settings'
    | '/app/tasks'
    | '/app/weighings'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/admin'
    | '/app/alerts'
    | '/app/animals'
    | '/app/applications'
    | '/app/finance'
    | '/app/harvests'
    | '/app/health'
    | '/app/plots'
    | '/app/reports'
    | '/app/seasons'
    | '/app/settings'
    | '/app/tasks'
    | '/app/weighings'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/app'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/alerts'
    | '/_authenticated/app/animals'
    | '/_authenticated/app/applications'
    | '/_authenticated/app/finance'
    | '/_authenticated/app/harvests'
    | '/_authenticated/app/health'
    | '/_authenticated/app/plots'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/seasons'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/tasks'
    | '/_authenticated/app/weighings'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/weighings': {
      id: '/_authenticated/app/weighings'
      path: '/weighings'
      fullPath: '/app/weighings'
      preLoaderRoute: typeof AuthenticatedAppWeighingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tasks': {
      id: '/_authenticated/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AuthenticatedAppTasksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seasons': {
      id: '/_authenticated/app/seasons'
      path: '/seasons'
      fullPath: '/app/seasons'
      preLoaderRoute: typeof AuthenticatedAppSeasonsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/plots': {
      id: '/_authenticated/app/plots'
      path: '/plots'
      fullPath: '/app/plots'
      preLoaderRoute: typeof AuthenticatedAppPlotsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/health': {
      id: '/_authenticated/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AuthenticatedAppHealthRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/harvests': {
      id: '/_authenticated/app/harvests'
      path: '/harvests'
      fullPath: '/app/harvests'
      preLoaderRoute: typeof AuthenticatedAppHarvestsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/finance': {
      id: '/_authenticated/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AuthenticatedAppFinanceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/applications': {
      id: '/_authenticated/app/applications'
      path: '/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AuthenticatedAppApplicationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/animals': {
      id: '/_authenticated/app/animals'
      path: '/animals'
      fullPath: '/app/animals'
      preLoaderRoute: typeof AuthenticatedAppAnimalsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alerts': {
      id: '/_authenticated/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AuthenticatedAppAlertsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppAlertsRoute: typeof AuthenticatedAppAlertsRoute
  AuthenticatedAppAnimalsRoute: typeof AuthenticatedAppAnimalsRoute
  AuthenticatedAppApplicationsRoute: typeof AuthenticatedAppApplicationsRoute
  AuthenticatedAppFinanceRoute: typeof AuthenticatedAppFinanceRoute
  AuthenticatedAppHarvestsRoute: typeof AuthenticatedAppHarvestsRoute
  AuthenticatedAppHealthRoute: typeof AuthenticatedAppHealthRoute
  AuthenticatedAppPlotsRoute: typeof AuthenticatedAppPlotsRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppSeasonsRoute: typeof AuthenticatedAppSeasonsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTasksRoute: typeof AuthenticatedAppTasksRoute
  AuthenticatedAppWeighingsRoute: typeof AuthenticatedAppWeighingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppAlertsRoute: AuthenticatedAppAlertsRoute,
  AuthenticatedAppAnimalsRoute: AuthenticatedAppAnimalsRoute,
  AuthenticatedAppApplicationsRoute: AuthenticatedAppApplicationsRoute,
  AuthenticatedAppFinanceRoute: AuthenticatedAppFinanceRoute,
  AuthenticatedAppHarvestsRoute: AuthenticatedAppHarvestsRoute,
  AuthenticatedAppHealthRoute: AuthenticatedAppHealthRoute,
  AuthenticatedAppPlotsRoute: AuthenticatedAppPlotsRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppSeasonsRoute: AuthenticatedAppSeasonsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTasksRoute: AuthenticatedAppTasksRoute,
  AuthenticatedAppWeighingsRoute: AuthenticatedAppWeighingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
